projectList = [
    {
        'id': 1, #####
        "ident": "R2223", #####
        "name": 'EP-WXT触发处理主控软件', #####
        "engin_model": "EP卫星", #####
        "section_system": '控制模块', #####
        "sub_system": "模式切换", #####
        "device": "龙芯",
        "beginTime": "2022-12-01", #####
        "endTime": "2023-12-31", #####
        "duty_person": "尧颖婷", #####
        "member": ['陈俊亦', '尧颖婷', '李鑫', '王光宗'], #####
        "security_level": '2', #####
        "test_level": ['1'], #####
        "plant_type": '1', #####
        "report_type": '2', #####
        "language": ['7'], #####
        "standard": ['1'], #####
        "entrust_ident": "上海翰讯科技股份有限公司",
        "entrust_legal": "xxx",
        "entrust_contact": "周童",
        "entrust_contact_phone": "13882947777",
        "entrust_email": "188@163.com",
        "dev_ident": "成都微米科技有限公司",
        "dev_legal": "xxx",
        "dev_contact": "周聪各",
        "dev_contact_phone": "13884509827",
        "dev_email": "13283647128@163.com",
        "test_ident": "成都微米科技有限公司",
        "test_legal": "中国科学院卫星软件测评中心",
        "test_contact": "施敏华",
        "test_contact_phone": "17725327187",
        "test_email": "17725327187@163.com",
        'step': '3' #####
    },
    {
        'id': 2,
        "ident": "R2133",
        "name": 'EP-WXT触发处理主控软件',
        "engin_model": "EP卫星",
        "section_system": '控制模块',
        "sub_system": "模式切换",
        "device": "龙芯",
        "beginTime": "2022-12-01",
        "endTime": "2023-12-31",
        "duty_person": "尧颖婷",
        "member": ['陈俊亦', '尧颖婷', '李鑫', '王光宗'],
        "security_level": '1',
        "test_level": ['1'],
        "plant_type": '1',
        "report_type": '2',
        "language": ['7'],
        "standard": ['1'],
        "entrust_ident": "上海翰讯科技股份有限公司",
        "entrust_legal": "xxx",
        "entrust_contact": "周童",
        "entrust_contact_phone": "13882947777",
        "entrust_email": "188@163.com",
        "dev_ident": "成都微米科技有限公司",
        "dev_legal": "xxx",
        "dev_contact": "周聪各",
        "dev_contact_phone": "13884509827",
        "dev_email": "13283647128@163.com",
        "test_ident": "成都微米科技有限公司",
        "test_legal": "中国科学院卫星软件测评中心",
        "test_contact": "施敏华",
        "test_contact_phone": "17725327187",
        "test_email": "17725327187@163.com",
        'step': '2'
    },
    {
        "ident": "R2423",
        'id': 3,
        "name": 'EP-WXT触发处理主控软件',
        "engin_model": "EP卫星",
        "section_system": '控制模块',
        "sub_system": "模式切换",
        "device": "龙芯",
        "beginTime": "2022-12-01",
        "endTime": "2023-12-31",
        "duty_person": "尧颖婷",
        "member": ['陈俊亦', '尧颖婷', '李鑫', '王光宗'],
        "security_level": '1',
        "test_level": ['1'],
        "plant_type": '1',
        "report_type": '2',
        "language": ['7'],
        "standard": ['1'],
        "entrust_ident": "上海翰讯科技股份有限公司",
        "entrust_legal": "xxx",
        "entrust_contact": "周童",
        "entrust_contact_phone": "13882947777",
        "entrust_email": "188@163.com",
        "dev_ident": "成都微米科技有限公司",
        "dev_legal": "xxx",
        "dev_contact": "周聪各",
        "dev_contact_phone": "13884509827",
        "dev_email": "13283647128@163.com",
        "test_ident": "成都微米科技有限公司",
        "test_legal": "中国科学院卫星软件测评中心",
        "test_contact": "施敏华",
        "test_contact_phone": "17725327187",
        "test_email": "17725327187@163.com",
        'step': '1'
    },
    {
        "ident": "F2214",
        'id': 4,
        "name": 'EP-WXT触发处理主控软件',
        "engin_model": "EP卫星",
        "section_system": '控制模块',
        "sub_system": "模式切换",
        "device": "龙芯",
        "beginTime": "2022-12-01",
        "endTime": "2023-12-31",
        "duty_person": "尧颖婷",
        "member": ['陈俊亦', '尧颖婷', '李鑫', '王光宗'],
        "security_level": '1',
        "test_level": ['1'],
        "plant_type": '1',
        "report_type": '2',
        "language": ['7'],
        "standard": ['1'],
        "entrust_ident": "上海翰讯科技股份有限公司",
        "entrust_legal": "xxx",
        "entrust_contact": "周童",
        "entrust_contact_phone": "13882947777",
        "entrust_email": "188@163.com",
        "dev_ident": "成都微米科技有限公司",
        "dev_legal": "xxx",
        "dev_contact": "周聪各",
        "dev_contact_phone": "13884509827",
        "dev_email": "13283647128@163.com",
        "test_ident": "成都微米科技有限公司",
        "test_legal": "中国科学院卫星软件测评中心",
        "test_contact": "施敏华",
        "test_contact_phone": "17725327187",
        "test_email": "17725327187@163.com",
        'step': '3'
    },
    {
        "ident": "R2123",
        "id": 5,
        "name": 'EP-WXT触发处理主控软件',
        "engin_model": "EP卫星",
        "section_system": '控制模块',
        "sub_system": "模式切换",
        "device": "龙芯",
        "beginTime": "2022-12-01",
        "endTime": "2023-12-31",
        "duty_person": "尧颖婷",
        "member": ['陈俊亦', '尧颖婷', '李鑫', '王光宗'],
        "security_level": '1',
        "test_level": ['1'],
        "plant_type": '1',
        "report_type": '2',
        "language": ['7'],
        "standard": ['1'],
        "entrust_ident": "上海翰讯科技股份有限公司",
        "entrust_legal": "xxx",
        "entrust_contact": "周童",
        "entrust_contact_phone": "13882947777",
        "entrust_email": "188@163.com",
        "dev_ident": "成都微米科技有限公司",
        "dev_legal": "xxx",
        "dev_contact": "周聪各",
        "dev_contact_phone": "13884509827",
        "dev_email": "13283647128@163.com",
        "test_ident": "成都微米科技有限公司",
        "test_legal": "中国科学院卫星软件测评中心",
        "test_contact": "施敏华",
        "test_contact_phone": "17725327187",
        "test_email": "17725327187@163.com",
        'step': '2'
    },
]
