# Generated by Django 4.1.7 on 2023-04-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjaapp', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
