# Generated by Django 4.1.7 on 2023-05-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjaapp', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
